theme: jekyll-theme-cayman
tittle: Suryansh Raj Gupta's Biography
description: A brief biography of Suryansh Raj Gupta that includes curated portfolio of my professional work of web apps, mobile apps, real client projects. Demonstrates my approach to problem solving, architecture, development workflows.